[package]
name = "determinate"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
#proc-macro2 = "^1.0.32"
futures = "^0.3.17"
quote = "^1.0.10"
syn = { version = "^1.0.81", features = ["full", "fold", "printing", "extra-traits"] }
